### ISSUE TITLE
Missing from Chrome webstore?

### ISSUE THREAD

**Issue by MarkWahlsten** [deathau/markdownload#117]
All links to Markdownload on the Chrome web store appear broken (Just get 404):

[MarkDownload - Markdown Web Clipper - Chrome Web Store](https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi)

404's on multiple browsers

Can't search for it manually, either.

**Comment by deathau** [comment]
Yeah, Google took it down due to "unused permissions" despite me being mid-conversation with them about which exact permission it is I wasn't using (it turns out I don't need `tabs` permission to read all tabs, which I thought I did).
It has been resubmitted a matter of hours ago and should be back up whenever they get around to reviewing it.
