### ISSUE TITLE
sufolder

### ISSUE THREAD

**Issue by hahagood** [deathau/markdownload#146]
Vivaldi	5.3.2679.58 (Stable channel) stable （64 bit）
version	866b85e22087e34531ed8892e87d6716dc004501
OS   	Linux
JavaScript	V8 10.2.154.8
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.125 Safari/537.36

In user manuel, I found:
'''
Subfolder
Only available if Download Mode is set to "Downloads API" (Not supported in Safari)
This specifies a subfolder within your downloads folder to save downloaded files. A security limitation of modern browsers prevents this folder being outside the browser's specified downloads folder. UtilUtilizes Customizes Custom Text Substitutions
'''
but:
If I gave the "Utilizes Custom Text Substitutions" = "webclipper"
when I saved somethin last time to folder ~/Downloads/subfolder1, the clipper be saved in ~/Downloads/subfolder1/webclipper/XXX.md
Next time I save something to folder  ~/Downloads/subfolder2, it will be in ~/Downloads/subfolder2/webclipper/XXX.md

**Comment by deathau** [comment]
That's expected behaviour.

The "Subfolder" setting specifies the subfolder your markdown file will be added to, _within the folder you download to_

So if you set that setting to "webclipper" (as in your example) then download to `~/Downloads/subfolder1`, the extension will append `webclipper/XXX.md` to that path to give you `~/Downloads/subfolder1/webclipper/XXX.md`
