### ISSUE TITLE
image filename is not correct

### ISSUE THREAD

**Issue by zen010101** [deathau/markdownload#52]
https://www.ershicimi.com/p/044d2f679d3289d3f615b4acf64db379

the image filename in the page above cann't be saved correctly.

**Comment by deathau** [comment]
Yeah, I see what the issue is there. Currently, I'm grabbing the image and saving it with its original file name, which according to the URL is something like `https://mmbiz.qpic.cn/mmbiz_png/oVibRetUmUanx9eDk5w4Qria3qTxhN0x5sAhVHRWeEZNelsKJtq0fx3Puu5vWoPWGSDYH3xdvUmGHEsW8uzcrkEw/640?wx_fmt=png`, the file name part of that is just "640".
I'll need to do a bit more work to make files like this have unique names and a proper extension based on image format. Which might be tricky, but should be possible.

**Comment by zen010101** [comment]
It really a GOOD news! :-)

**Comment by deathau** [comment]
This should be resolved as of 3.0.0
