### ISSUE TITLE
I thought it was FREE?

### ISSUE THREAD

**Issue by vincentyang116** [deathau/markdownload#86]
Hi there,
Thanks for your work! But I thought the extension would be free to use forever?
<img width="356" alt="截屏2021-05-20 上午9 42 08" src="https://user-images.githubusercontent.com/38676561/118906110-acf19300-b94f-11eb-959e-fc4ce228dbd5.png">

**Comment by deathau** [comment]
It's free on Firefox and Chromium based browsers (such as Chrome and Edge).
Unfortunately, in order to publish on Safari, I need to pay for a developer license, which is a yearly thing. I'm hoping charging for the extension on Safari will help cover that cost. 
I was reluctant to do so, but there were others who were indicating they'd be willing to pay and the alternative was to just _not_ have a Safari version

**Comment by vincentyang116** [comment]
All right, got it. Thanks again, I'm willing to pay too, chrome is performance consuming on mac for me.&nbsp;
Also, maybe you should change the words in README to avoid being confusing, I thought it's Apple want me to pay, hahaha..




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月20日(星期四) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [deathau/markdownload] I thought it was FREE? (#86)





 
It's free on Firefox and Chromium based browsers (such as Chrome and Edge).
 Unfortunately, in order to publish on Safari, I need to pay for a developer license, which is a yearly thing. I'm hoping charging for the extension on Safari will help cover that cost.
 I was reluctant to do so, but there were others who were indicating they'd be willing to pay and the alternative was to just not have a Safari version

**Comment by deathau** [comment]
Oh damn, I never updated the README. Thanks for pointing that out!
